import type { DeckCandidate } from "@/lib/types";

let n = 0;
export function car(overrides: Partial<DeckCandidate> = {}): DeckCandidate {
  n += 1;
  return {
    id: `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`,
    vin: "1HGCM82633A004352",
    year: 2021,
    make: "Toyota",
    model: "RAV4",
    trim_level: "XLE",
    body_style: "compact_suv",
    condition: "used",
    price: 26000,
    msrp: 30000,
    expected_price: 27000,
    deal_rating: "good",
    miles: 40000,
    exterior_color: "Blueprint",
    exterior_color_family: "blue",
    interior_color: "Black",
    interior_material: "cloth",
    fuel_type: "gas",
    drivetrain: "awd",
    transmission: "automatic",
    engine: "2.5L I4",
    horsepower: 203,
    mpg_city: 27,
    mpg_hwy: 35,
    ev_range_mi: null,
    seats: 5,
    third_row: false,
    towing_lbs: 1500,
    features: ["carplay", "heated_seats"],
    features_verified: true,
    title_status: "clean",
    accident_count: 0,
    owner_count: 1,
    personal_use: true,
    open_recalls: 0,
    days_on_market: 12,
    last_price_drop: null,
    photos: ["/fx/car/compact_suv/2b4a7e/0"],
    photo_count: 4,
    quality_score: 0.7,
    seller_type: "dealer",
    source: "fixture",
    source_url: null,
    zip: "37206",
    dealership_id: `d-${n}`,
    dealer_name: "Test Motors",
    dealer_doc_fee: 599,
    dealer_lead_channel: "inbox",
    dealer_response_minutes: 30,
    distance_mi: 8,
    visual_sim: null,
    is_exploration: false,
    is_promoted: false,
    ...overrides,
  };
}
